### ISSUE TITLE
Relax Dropdown CWRP value error for multiple dropdowns

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#309]
In CWRP this assumes the dropdown has a value prop, and throws an error in dev mode if it is not an array.  We need to ensure nextProps _.has() a value before throwing errors over it.  Without a value, it is self controlled.

``` js
if (nextProps.multiple && !isNextValueArray) {
  console.error(
    'Dropdown `value` must be an array when `multiple` is set.' +
    ` Received type: \`${Object.prototype.toString.call(nextProps.value)}\`.`,
  )
} else if (!nextProps.multiple && isNextValueArray) {
  console.error(
    'Dropdown `value` must not be an array when `multiple` is not set.' +
    ' Either set `multiple={true}` or use a string or number value.'
  )
}
```

**Comment by levithomason** [comment]
Fixed in #310

**Comment by lxm7** [comment]
Is there a way to suppress this warning completely? I'm passing it an array in `value={field.value}` on the dropdown component for either single or mutliple selected values but still getting `Dropdown `value` must be an array when `multiple` is set. Received type: `[object Null]`
