### ISSUE TITLE
Modal: size="fullscreen" sticks to left 

### ISSUE THREAD

**Issue by argoyb** [Semantic-Org/Semantic-UI-React#3345]
### Steps
1. Go to https://react.semantic-ui.com/modules/modal/#variations-size
1. Click on "Fullscreen"

### Expected Result
Expected popup to be centered
![screen shot 2018-12-19 at 4 41 17 pm](https://user-images.githubusercontent.com/35706103/50256809-f28b8980-03ac-11e9-8578-1c0120794782.png)

### Actual Result
Popup sticks to left border
![screen shot 2018-12-19 at 4 41 25 pm](https://user-images.githubusercontent.com/35706103/50256815-fc14f180-03ac-11e9-8266-206e34494f93.png)

### Version
v0.84.0

### Testcase
Please see https://react.semantic-ui.com/modules/modal/#variations-size

**Comment by argoyb** [comment]
WebInspector shows `left: 0!important;` property for `.ui.fullscreen.modal` which seems to cause the issue

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/issues/3289#issuecomment-440224606

We should temporary switch our docs to `semantic-ui` package.

**Comment by shamin** [comment]
@layershifter I think this one is fixed in https://github.com/Semantic-Org/Semantic-UI/commit/36d5857eaba7e6a51ca522521f8505f5c343405c

**Comment by KunleMichaels** [comment]
has this issue been fixed? i'm new to open source and i will like to take this as my first issue

**Comment by layershifter** [comment]
To clarify the issue:
- this bug was fixed in Semantic UI 2.4.1, https://github.com/Semantic-Org/Semantic-UI/commit/36d5857eaba7e6a51ca522521f8505f5c343405c
- `semantic-ui-css@2.4.2` and `semantic-ui-less@2.4.2` aren't published to NPM, https://github.com/Semantic-Org/Semantic-UI/issues/6646
- `semantic-ui@2.4.1` and `semantic-ui-css@2.4.1` has wrong prebuilt CSS and it points to [2.4.0](https://cdn.jsdelivr.net/npm/semantic-ui-css@2.4.1/semantic.min.css) which contains this bug 😭 

I made a PR (#3367) that will fix this issue for our doc site. For users: please ensure that you're really using SUI 2.4.2.

**Comment by zigacernigoj** [comment]
Just a reminder. The issue is still present in **semantic-ui-react 0.86.0**, because it uses **semantic-ui-css 2.4.1** 
Thought it was fixed as the issue is closed and PR merged.

**Comment by brandonryan** [comment]
This is still an issue in semantic-ui-react 0.88. @layershifter should this issue be re-opened?
