### ISSUE TITLE
Homepage layout problem

### ISSUE THREAD

**Issue by username7171** [Semantic-Org/Semantic-UI-React#3398]
I think there is a bug in the official demonstration in semantic-ui-react

https://react.semantic-ui.com/layouts/homepage/

It is Okay when you open it the first time, however, when you refresh the page, it becomes messy. Where is the bug? 

A clear and concise description of steps to reproduce the problem.

### Expected Result
![image](https://user-images.githubusercontent.com/36737465/51613889-76620400-1f5f-11e9-9cf8-c63b018f4f59.png)

### Actual Result
![image](https://user-images.githubusercontent.com/36737465/51613901-7eba3f00-1f5f-11e9-8e52-e3b88c83a7d5.png)

**Comment by layershifter** [comment]
Was fixed in #3373.

**Comment by username7171** [comment]
> Was fixed in #3373.
Sorry but I think the bug remains,
I have downloaded the code and run on local to test it. 
You can also try to visit 
https://react.semantic-ui.com/layouts/homepage/
and refresh the page to reproduce the bug.

**Comment by layershifter** [comment]
It was fixed, but was not released yet 🏷  Served locally (`yarn build:docs:staging`) production build and everything is fine there:

![image](https://user-images.githubusercontent.com/14183168/51618372-dee8bb00-1f36-11e9-84a6-64c285f26d9e.png)

**Comment by username7171** [comment]
Thanks so much for your reply. May I ask one silly question?
![image](https://user-images.githubusercontent.com/36737465/51619227-d27e5580-1f6a-11e9-9f9a-af3edac70ac1.png)
There are 3 files changed corresponding to this issue.
I am already using the updated version of the middle file , which is HomepageLayout.js.
But the bug remains. Is it because HomepageLayout.js. file rely on the first and third file?

**Comment by layershifter** [comment]
> But the bug remains.

Sorry, what do you mean? I don't understand. You have issues with `Responsive` and SSR?
Please check https://github.com/Semantic-Org/Semantic-UI-React/issues/3361#issuecomment-453202401 and https://codesandbox.io/s/ly3zpw7yzm

**Comment by username7171** [comment]
Oh.Thank you so much. All 3 solutions provided by you are great. The NoSSR component works perfectly.
