### ISSUE TITLE
DropDown cannot close and the Textarea cannot input the space

### ISSUE THREAD

**Issue by konantian** [Semantic-Org/Semantic-UI-React#3689]
### Steps
I have a form component in the dropdown list, when each time the user click the items in the dropdown list, it will open a new form. The dropdown should be closed at this time, but sometimes it cannot close correctly. After I open the form, if there is TextArea in this form, it cannt input space

### Expected Result
When I click the items in the dropdown list, the dropdown should close, and after I open the form, the TextArea should allow the user to input the sapce

### Actual Result
Dropdown cannot close sometimes, the form cannot input space

**Comment by mbosecke** [comment]
Here's a sandbox example where a user can't enter a space character:

https://codesandbox.io/s/semantic-ui-react-example-oyk36?fontsize=14

**Comment by layershifter** [comment]
It's a duplicate of two odd bugs:
#3146
#3174

For workaround you can use controlled `Modal` and use it outside `Dropdown`.

**Comment by jgonik** [comment]
Hi,

Sorry if this is a simple question, but could you please provide an example of the workaround? I'm not entirely sure what you mean.

Thanks so much!

**Comment by layershifter** [comment]
@jgonik I can't reproduce this issue with `1.1.1`: https://codesandbox.io/s/semantic-ui-react-example-oyk36?fontsize=14

Do you have a repro CodeSandbox? 😺

**Comment by jgonik** [comment]
Never mind, I figured it out! Thanks so much :)

**Comment by oldmcdonalds** [comment]
@layershifter i am still not able to type in spaces in the code sandbox you shared above:  https://codesandbox.io/s/semantic-ui-react-example-oyk36?fontsize=14

Am i missing something?

**Comment by layershifter** [comment]
@aakashgupta0205 shame on me 🤦 I double verified and the issue **exists** in `1.2.0` (https://codesandbox.io/s/semantic-ui-react-example-forked-t2l25), reopened...

**Comment by layershifter** [comment]
A fix was released in `semantic-ui-react@1.2.1` 🎉

**Comment by SaraMSchwarz** [comment]
I'm still unable to use spaces within a TextArea, even after updating to latest release.

**Comment by layershifter** [comment]
@SaraMSchwarz Please share a repro on CodeSandbox and steps to repro. I checked with latest (https://codesandbox.io/s/semantic-ui-react-example-forked-t2l25) and it works as expected.

![dropdown-space](https://user-images.githubusercontent.com/14183168/92098602-bfd03180-edd9-11ea-85e9-15fd22435c98.gif)

**Comment by takwing** [comment]
I still cannot type space in an input field under a dropdown, code https://codesandbox.io/s/semantic-ui-react-forked-bgvqj.

Not sure what is wrong.  Using v1.3.1 already

**Comment by layershifter** [comment]
@takwing I've seen that you have created a separate issue #4142, let's track it there.
