### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf;charset=utf-8

### ISSUE THREAD

**Issue by sergeushenecz** [Semantic-Org/Semantic-UI-React#4227]
### Steps
After upgrade css-loader to last version 6.0.0 i have error 
Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf;charset=utf-8;;base64,
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "data:" URIs.

**semantic.min.css** if remove extra semicolon in min.css 
![image](https://user-images.githubusercontent.com/7217517/125836083-708c524d-ccd6-4030-86a8-5d38888466a3.png)
then compile success. But all icons not showing

### Expected Result
Compile without errors

### Actual Result
Errors

### Version
last version 

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by sergeushenecz** [comment]
Fixed how write in the https://github.com/webpack-contrib/css-loader/issues/1338 remove deprecated loaders.

**Comment by sergeu90** [comment]
Removed Deprecated modules.

**Comment by sergeushenecz** [comment]
but semantic.min.css if remove extra semicolon in min.css to need fix. I apply patch.

**Comment by Gamerweazel** [comment]
@sergeu90 I have same issue, removing semicolon fixes it.

**Comment by layershifter** [comment]
Folks, this looks like a valid issue, but we don't maintain CSS in this repo (only React components) so there is no action from our side 😥

**Comment by dayflower** [comment]
JFYI: this issue seems to be fixed in the following PR of **Fo**mantic-UI. (but not yet released to npm registry)
https://github.com/fomantic/Fomantic-UI/pull/2028

**Comment by lubber-de** [comment]
you can use the nightly build where this is already fixed and deployed on npm
```terminal
npm install --ignore-scripts fomantic-ui@nightly
```

Also stated in the docs
https://fomantic-ui.com/introduction/getting-started.html

**Comment by MatissJanis** [comment]
For people (such as me) still looking for a proper solution: https://github.com/Semantic-Org/Semantic-UI-CSS/issues/75

**Comment by layershifter** [comment]
I implemented small tool to patch files to avoid the issue, https://github.com/Semantic-Org/Semantic-UI-React/issues/4287#issuecomment-1016579332

**Comment by bubbaspaarx** [comment]
> I implemented small tool to patch files to avoid the issue, [#4287 (comment)](https://github.com/Semantic-Org/Semantic-UI-React/issues/4287#issuecomment-1016579332)

I am still receiving an error. I believe it's related to the 'step.overrides' file. The URL appears to be the same as the original semantic.css + step.css files. The double semi-colon appears still

**Comment by tdd** [comment]
Hey all, FWIW fomantic-ui doesn't maintain its nightly dist-tag anymore, so we don't have access to the fix. The on-postinstall [patch tool](https://github.com/layershifter/semantic-ui-tools/tree/master/packages/css-patch) by a third party is the only workable solution so far… Gawd the maintenance state of SUI is abysmal…

Thanks for all your valiant efforts though! 👍

**Comment by lubber-de** [comment]
> Hey all, FWIW fomantic-ui doesn't maintain its nightly dist-tag anymore, so we don't have access to the fix.

That's not correct. fomantic ui main repo still creates nightly builds, but only if there was a change in the develop branch.

**Comment by tdd** [comment]
Hey there! Thanks for the info.

I was mistaken as I'm using `fomantic-ui-css` (not `fomantic-ui`), that doesn't match the nightly dist-tag of `fomantic-ui` apparently.

**Comment by lubber-de** [comment]
Yes , only the main repo has a nightly build script. The less and css repos only get updates upon an official release. We might investigate to improve that for a nightly tag on those repos as well.
Help appreciated 😉

2.9.0 is on it's way. But you can always fetch the css file out of the main repo nightly build if needed.
