### ISSUE TITLE
Popup, initial position in React ^18.x.x. Initial jumping.

### ISSUE THREAD

**Issue by optimus-sma** [Semantic-Org/Semantic-UI-React#4350]
## Bug Report
Popup has fixed initial position on the screen.

### Steps
Problem happens in Popup with on='hover'

### Expected Result
Popup position near trigger element based on position property.

### Actual Result
Top/left screen position for a few ms. 

### Version
2.1.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-ky6fpt?file=/index.js

**Comment by optimus-sma** [comment]
To prevent it I have added:

.ui.popup {
  animation-delay: 0.1s;
  animation-duration: 0.1s;
  animation-name: hover;
}

@keyframes hover{
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

**Comment by therealgilles** [comment]
I am experiencing the same issue. And the problem may lie with Popper.js or React.

**Comment by optimus-sma** [comment]
> I am experiencing the same issue. And the problem may lie with Popper.js or React.

Right, new React batching in async functions...

**Comment by layershifter** [comment]
I guess the problem is with [`react-popper`](https://github.com/floating-ui/react-popper) and changes in React. I haven't debug that problem yet, so if someone is willing it would be great 🐱

**Comment by therealgilles** [comment]
From what I can gather so far, there is a race between the 'display: flex' and the 'transform: transform3d(...)' and the transform3d is behind with React 18, creating the jumping effect.

The first pass adds the following to the DOM:
```HTML
<div style="display: flex; position: absolute; left: 0px; top: 0px; z-index: 1900;">
    <div class="ui top right large inverted popup transition visible" style="left: auto; right: auto; position: initial;">
        <div class="content">...</div>
    </div>
</div>
```

and then a second pass with the whole html code:
```HTML
<div style="display: flex; position: absolute; inset: 0px auto auto 0px; z-index: 1900; transform: translate3d(1170px, 52.5px, 0px);">
    <div class="ui bottom right large inverted popup transition visible" style="left: auto; right: auto; position: initial;">
        <div class="content">...</div>
    </div>
</div>
```

**Comment by therealgilles** [comment]
Stepping through renderContent in node_modules/semantic-ui-react/dist/commonjs/modules/Popup/Popup.js, I see it getting called multiple times, but actually the same way on React 17 vs 18. It looks like the problem may have been there all along, but React 18 is faster at rendering.

**Comment by therealgilles** [comment]
Here is a possible for react-popper/lib/esm/usePopper.js:

```JS
  // ADDED
  var defaultStyles = {
    popper: {
      left: '0',
      top: '0'
    }
  }

  var _React$useState = React.useState({
    styles: {
      popper: {
        position: optionsWithDefaults.strategy,
        // left: '0',  -- REMOVED
        // top: '0',  -- REMOVED
      }
    },
    attributes: {}
  }),

      state = _React$useState[0],
      setState = _React$useState[1];

  var updateStateModifier = React.useMemo(function () {
    return {
      name: 'updateState',
      enabled: true,
      phase: 'write',
      fn: function fn(_ref) {
        var state = _ref.state;
        var elements = Object.keys(state.elements);
        setState({
          // styles: fromEntries(elements.map(function (element) {
          //   return [element, state.styles[element] || {}];
          // })),
          // ADDED defaultStyles here
          styles: { ...defaultStyles, ...fromEntries(elements.map(function (element) {
            return [element, state.styles[element] || {}];
          })) },
          attributes: fromEntries(elements.map(function (element) {
            return [element, state.attributes[element]];
          }))
        });
      },
      requires: ['computeStyles']
    };
  }, []);
```

Not sure if this is the right fix, but removing top/left as defaults prevents the popup from being displayed too early in the wrong location.

**Comment by therealgilles** [comment]
There is a react-popper issue already opened: https://github.com/floating-ui/react-popper/issues/349

**Comment by layershifter** [comment]
It seems that the solution exists, https://github.com/floating-ui/react-popper/pull/440 🎉

**Comment by therealgilles** [comment]
What's the right way to update react-popper for Semantic-UI-React then? should the fixed version (2.3.0?) be installed manually?

**Comment by ben-rogerson** [comment]
Here's my hacky workaround until I can add popper as a peer dep: 
(I'm aware of the fragile selectors)

```css
/* Hacky workaround for Popup displaying briefly due to React 18 updates.
https://github.com/Semantic-Org/Semantic-UI-React/issues/4350
TODO: Remove this hack once semantic-ui-react supports adding peerDependencies:
https://github.com/Semantic-Org/Semantic-UI-React/issues/4354
The hack below hides the Portal element until the component adds the inset style: */

body:last-child div[style^='display: flex; position: absolute;'] & {
    visibility: hidden !important;
}
body:last-child div[style^='display: flex; position: absolute; inset: 0px auto auto 0px;'] &,
body:last-child div[style^='display: flex; position: absolute; inset: auto auto 0px 0px;'] & {
    visibility: visible !important;
}
```

**Comment by layershifter** [comment]
The fix was released in `semantic-ui-react@2.1.3`.

**Comment by varand-pez** [comment]
this is still happening for me. 
React: 18.2.0
semantic: 2.1.3

Update:
After some more debugging I realized the issue is happening because the popup is rendered inside `TransitionablePortal`.
